version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: titanic_api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models:ro
      - ../../data:/app/data:ro
    restart: unless-stopped

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    container_name: titanic_app
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ../../models:/app/models:ro
    restart: unless-stopped
